// Generated by scripts/build-brand-assets.py. The hash is of the image's own bytes, so a
// new picture is a new URL and no cache anywhere can serve the previous one.
export const OG_IMAGE = "/og-81ee59bef8.png";
